wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1678827305
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      4: 3.9.5
      5: 0.12.14
      8:
      - 5
batch_size:
  desc: null
  value: 128
epochs:
  desc: null
  value: 20
eval_metric_name:
  desc: null
  value: ssim
learning_rate:
  desc: null
  value: 0.0001
seed:
  desc: null
  value: 42
weight_decay:
  desc: null
  value: 1.0e-15
wrap_size:
  desc: null
  value: 32
