model:

  input_channels: 1
  out_channels: 1
  layers:
    - name: Encoder
      type: module
      out_channels: 192
      layers:
        - name: block1
          type: module
          out_channels: 384
          layers:
            - name: conv1 
              type: conv
              out_channels: 384
              kernel_size: 5
              stride: 1
              padding: 2
            - name: maxpool1
              type: maxpool
              output_shape: 8
            - name: gelu
              type: gelu
        - name: block2
          type: module
          out_channels: 768
          layers:
            - name: conv2
              type: conv
              out_channels: 768
              kernel_size: 5
              stride: 1
              padding: 2
            - name: maxpool2
              type: maxpool
              output_shape: 2
            - name: gelu
              type: gelu
        - name: block3
          type: module
          out_channels: 192
          layers:
            - name: conv3
              type: conv
              out_channels: 192
              kernel_size: 1
              stride: 1
              padding: 0
            - name: gelu
              type: gelu
        - name: droupout
          type: dropout
          out_channels: 192
          shape: 
            - -1
            - 768
          rate: 0.1
    - name: Decoder
      type: module
      out_channels: 192
      layers:
        - name: reshape
          type: reshape
          shape:
            - -1
            - 192
            - 2
            - 2
        - name: de_block1
          type: module
          out_channels: 48
          layers: 
            - name: deconv1
              type: deconv
              out_channels: 48
              kernel_size: 2
              stride: 2
            - name: leaky_relu
              type: leaky_relu
              slope: 0.2
        - name: de_block2
          type: module
          out_channels: 12
          layers: 
            - name: deconv2
              type: deconv
              out_channels: 12
              kernel_size: 2
              stride: 2
            - name: leaky_relu
              type: leaky_relu
              slope: 0.2
        - name: de_block3
          type: module
          out_channels: 4
          layers: 
            - name: deconv3
              type: deconv
              out_channels: 4
              kernel_size: 2
              stride: 2
            - name: leaky_relu
              type: leaky_relu
              slope: 0.2
        - name: block4
          type: module
          out_channels: 4
          layers: 
            - name: conv1
              type: conv
              out_channels: 4
              kernel_size: 3
              stride: 1
              padding: 1
            - name: leaky_relu
              type: leaky_relu
              slope: 0.2
        - name: de_block5
          type: module
          out_channels: 1
          layers: 
            - name: deconv4
              type: deconv
              out_channels: 1
              kernel_size: 2
              stride: 2
            - name: leaky_relu
              type: leaky_relu
              slope: 0.2
        - name: output_filter
          type: module
          out_channels: 1
          layers: 
            - name: conv2
              type: conv
              out_channels: 1
              kernel_size: 3
              stride: 1
              padding: 1
            - name: sigmoid
              type: sigmoid